// <auto-generated />
namespace OutlookFW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class edit_token_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_token_2));
        
        string IMigrationMetadata.Id
        {
            get { return "202105250922244_edit_token_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
